# Generated by Django 5.2.6 on 2025-09-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
