# Generated by Django 5.2.6 on 2025-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0002_alter_question_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
