# Generated by Django 5.2.6 on 2025-09-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0003_alter_question_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="created_at",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="created_at",
            new_name="create_date",
        ),
    ]
